# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

version30   = 'newlib-3.0.0.20180831'
version25   = 'newlib-2.5.0.20171222'
newlib_path = version30

libc_src = Split('''
newlib/libc/syscalls/sysfstat.c
newlib/libc/syscalls/sysfork.c
newlib/libc/syscalls/syssbrk.c
newlib/libc/syscalls/sysstat.c
newlib/libc/syscalls/syswait.c
newlib/libc/syscalls/syswrite.c
newlib/libc/syscalls/sysisatty.c
newlib/libc/syscalls/sysgettod.c
newlib/libc/syscalls/systimes.c
newlib/libc/syscalls/syslink.c
newlib/libc/syscalls/sysunlink.c
newlib/libc/syscalls/sysexecve.c
newlib/libc/syscalls/sysopen.c
newlib/libc/syscalls/sysgetpid.c
newlib/libc/syscalls/syslseek.c
newlib/libc/syscalls/sysclose.c
newlib/libc/syscalls/syskill.c
newlib/libc/syscalls/sysfcntl.c
newlib/libc/syscalls/sysread.c
newlib/libc/reent/signgam.c
newlib/libc/reent/gettimeofdayr.c
newlib/libc/reent/signalr.c
newlib/libc/reent/linkr.c
newlib/libc/reent/writer.c
newlib/libc/reent/fstatr.c
newlib/libc/reent/unlinkr.c
newlib/libc/reent/closer.c
newlib/libc/reent/readr.c
newlib/libc/reent/sbrkr.c
newlib/libc/reent/isattyr.c
newlib/libc/reent/execr.c
newlib/libc/reent/mkdirr.c
newlib/libc/reent/lseekr.c
newlib/libc/reent/statr.c
newlib/libc/reent/timesr.c
newlib/libc/reent/renamer.c
newlib/libc/reent/reent.c
newlib/libc/reent/impure.c
newlib/libc/reent/fcntlr.c
newlib/libc/reent/getreent.c
newlib/libc/reent/openr.c
newlib/libc/signal/psignal.c
newlib/libc/signal/raise.c
newlib/libc/signal/signal.c
newlib/libc/ctype/iswalnum_l.c
newlib/libc/ctype/iswgraph.c
newlib/libc/ctype/tolower.c
newlib/libc/ctype/iswxdigit.c
newlib/libc/ctype/iswprint_l.c
newlib/libc/ctype/iswcntrl.c
newlib/libc/ctype/isxdigit_l.c
newlib/libc/ctype/isupper.c
newlib/libc/ctype/isspace.c
newlib/libc/ctype/iswalpha.c
newlib/libc/ctype/iswalpha_l.c
newlib/libc/ctype/iswupper.c
newlib/libc/ctype/towctrans.c
newlib/libc/ctype/isupper_l.c
newlib/libc/ctype/isalnum.c
newlib/libc/ctype/toascii_l.c
newlib/libc/ctype/iswalnum.c
newlib/libc/ctype/iswctype.c
newlib/libc/ctype/islower.c
newlib/libc/ctype/isxdigit.c
newlib/libc/ctype/isascii.c
newlib/libc/ctype/isdigit.c
newlib/libc/ctype/wctype.c
newlib/libc/ctype/isblank_l.c
newlib/libc/ctype/ctype_.c
newlib/libc/ctype/iswgraph_l.c
newlib/libc/ctype/iswpunct.c
newlib/libc/ctype/iswblank_l.c
newlib/libc/ctype/isblank.c
newlib/libc/ctype/isspace_l.c
newlib/libc/ctype/iswdigit.c
newlib/libc/ctype/iswspace_l.c
newlib/libc/ctype/isascii_l.c
newlib/libc/ctype/towupper.c
newlib/libc/ctype/iswspace.c
newlib/libc/ctype/towlower_l.c
newlib/libc/ctype/isprint.c
newlib/libc/ctype/iswcntrl_l.c
newlib/libc/ctype/islower_l.c
newlib/libc/ctype/ispunct_l.c
newlib/libc/ctype/tolower_l.c
newlib/libc/ctype/isalpha_l.c
newlib/libc/ctype/isalpha.c
newlib/libc/ctype/towupper_l.c
newlib/libc/ctype/wctrans.c
newlib/libc/ctype/iscntrl.c
newlib/libc/ctype/iswlower.c
newlib/libc/ctype/iswlower_l.c
newlib/libc/ctype/iswblank.c
newlib/libc/ctype/ispunct.c
newlib/libc/ctype/isdigit_l.c
newlib/libc/ctype/iswctype_l.c
newlib/libc/ctype/iswpunct_l.c
newlib/libc/ctype/iswupper_l.c
newlib/libc/ctype/towctrans_l.c
newlib/libc/ctype/wctrans_l.c
newlib/libc/ctype/toupper.c
newlib/libc/ctype/toascii.c
newlib/libc/ctype/wctype_l.c
newlib/libc/ctype/iscntrl_l.c
newlib/libc/ctype/toupper_l.c
newlib/libc/ctype/iswdigit_l.c
newlib/libc/ctype/isalnum_l.c
newlib/libc/ctype/iswprint.c
newlib/libc/ctype/iswxdigit_l.c
newlib/libc/ctype/towlower.c
newlib/libc/ctype/jp2uc.c
newlib/libc/ctype/isprint_l.c
newlib/libc/stdlib/wcstoul.c
newlib/libc/stdlib/sb_charsets.c
newlib/libc/stdlib/putenv.c
newlib/libc/stdlib/atoll.c
newlib/libc/stdlib/erand48.c
newlib/libc/stdlib/rand_r.c
newlib/libc/stdlib/wcstoll.c
newlib/libc/stdlib/reallocarray.c
newlib/libc/stdlib/l64a.c
newlib/libc/stdlib/mprec.c
newlib/libc/stdlib/atexit.c
newlib/libc/stdlib/strtol.c
newlib/libc/stdlib/jrand48.c
newlib/libc/stdlib/freer.c
newlib/libc/stdlib/mbsnrtowcs.c
newlib/libc/stdlib/getsubopt.c
newlib/libc/stdlib/strtoull_r.c
newlib/libc/stdlib/ldiv.c
newlib/libc/stdlib/strtoumax.c
newlib/libc/stdlib/div.c
newlib/libc/stdlib/mbtowc.c
newlib/libc/stdlib/ldtoa.c
newlib/libc/stdlib/setenv.c
newlib/libc/stdlib/wcstold.c
newlib/libc/stdlib/gdtoa-hexnan.c
newlib/libc/stdlib/mbrlen.c
newlib/libc/stdlib/strtodg.c
newlib/libc/stdlib/msizer.c
newlib/libc/stdlib/malign.c
newlib/libc/stdlib/mblen.c
newlib/libc/stdlib/lldiv.c
newlib/libc/stdlib/on_exit.c
newlib/libc/stdlib/__exp10.c
newlib/libc/stdlib/__ten_mu.c
newlib/libc/stdlib/quick_exit.c
newlib/libc/stdlib/cxa_finalize.c
newlib/libc/stdlib/system.c
newlib/libc/stdlib/wcstoll_r.c
newlib/libc/stdlib/getopt.c
newlib/libc/stdlib/setenv_r.c
newlib/libc/stdlib/on_exit_args.c
newlib/libc/stdlib/wcstod.c
newlib/libc/stdlib/pvallocr.c
newlib/libc/stdlib/_Exit.c
newlib/libc/stdlib/a64l.c
newlib/libc/stdlib/malloptr.c
newlib/libc/stdlib/wcstoull_r.c
newlib/libc/stdlib/atol.c
newlib/libc/stdlib/random.c
newlib/libc/stdlib/wcstombs.c
newlib/libc/stdlib/strtoul.c
newlib/libc/stdlib/efgcvt.c
newlib/libc/stdlib/wcstoumax.c
newlib/libc/stdlib/mrand48.c
newlib/libc/stdlib/wcstoull.c
newlib/libc/stdlib/mbstowcs.c
newlib/libc/stdlib/__adjust.c
newlib/libc/stdlib/aligned_alloc.c
newlib/libc/stdlib/mallstatsr.c
newlib/libc/stdlib/wcsrtombs.c
newlib/libc/stdlib/mbsinit.c
newlib/libc/stdlib/reallocr.c
newlib/libc/stdlib/drand48.c
newlib/libc/stdlib/nrand48.c
newlib/libc/stdlib/rand48.c
newlib/libc/stdlib/environ.c
newlib/libc/stdlib/getenv_r.c
newlib/libc/stdlib/btowc.c
newlib/libc/stdlib/labs.c
newlib/libc/stdlib/ecvtbuf.c
newlib/libc/stdlib/arc4random_uniform.c
newlib/libc/stdlib/callocr.c
newlib/libc/stdlib/putenv_r.c
newlib/libc/stdlib/utoa.c
newlib/libc/stdlib/wctob.c
newlib/libc/stdlib/wcstoimax.c
newlib/libc/stdlib/atof.c
newlib/libc/stdlib/assert.c
newlib/libc/stdlib/llabs.c
newlib/libc/stdlib/mbsrtowcs.c
newlib/libc/stdlib/rand.c
newlib/libc/stdlib/vallocr.c
newlib/libc/stdlib/abort.c
newlib/libc/stdlib/wcsnrtombs.c
newlib/libc/stdlib/getenv.c
newlib/libc/stdlib/valloc.c
newlib/libc/stdlib/abs.c
newlib/libc/stdlib/calloc.c
newlib/libc/stdlib/mbtowc_r.c
newlib/libc/stdlib/mstats.c
newlib/libc/stdlib/atoff.c
newlib/libc/stdlib/atoi.c
newlib/libc/stdlib/imaxabs.c
newlib/libc/stdlib/mbrtowc.c
newlib/libc/stdlib/malloc.c
newlib/libc/stdlib/rpmatch.c
newlib/libc/stdlib/strtoull.c
newlib/libc/stdlib/cxa_atexit.c
newlib/libc/stdlib/seed48.c
newlib/libc/stdlib/wcrtomb.c
newlib/libc/stdlib/malignr.c
newlib/libc/stdlib/exit.c
newlib/libc/stdlib/dtoa.c
newlib/libc/stdlib/itoa.c
newlib/libc/stdlib/strtoll_r.c
newlib/libc/stdlib/__atexit.c
newlib/libc/stdlib/wcstombs_r.c
newlib/libc/stdlib/dtoastub.c
newlib/libc/stdlib/arc4random.c
newlib/libc/stdlib/mlock.c
newlib/libc/stdlib/reallocf.c
newlib/libc/stdlib/cfreer.c
newlib/libc/stdlib/mtrim.c
newlib/libc/stdlib/lcong48.c
newlib/libc/stdlib/realloc.c
newlib/libc/stdlib/wctomb_r.c
newlib/libc/stdlib/mbstowcs_r.c
newlib/libc/stdlib/wcstol.c
newlib/libc/stdlib/strtod.c
newlib/libc/stdlib/mallocr.c
newlib/libc/stdlib/envlock.c
newlib/libc/stdlib/__call_atexit.c
newlib/libc/stdlib/strtold.c
newlib/libc/stdlib/gdtoa-gethex.c
newlib/libc/stdlib/mallinfor.c
newlib/libc/stdlib/msize.c
newlib/libc/stdlib/strtoll.c
newlib/libc/stdlib/strtoimax.c
newlib/libc/stdlib/imaxdiv.c
newlib/libc/stdlib/srand48.c
newlib/libc/stdlib/mblen_r.c
newlib/libc/stdlib/wctomb.c
newlib/libc/stdlib/strtorx.c
newlib/libc/stdlib/eprintf.c
newlib/libc/stdlib/lrand48.c
newlib/libc/search/qsort.c
newlib/libc/search/tdestroy.c
newlib/libc/search/bsd_qsort_r.c
newlib/libc/search/hash_page.c
newlib/libc/search/hash.c
newlib/libc/search/tfind.c
newlib/libc/search/hcreate_r.c
newlib/libc/search/tsearch.c
newlib/libc/search/qsort_r.c
newlib/libc/search/tdelete.c
newlib/libc/search/hash_bigkey.c
newlib/libc/search/bsearch.c
newlib/libc/search/hash_log2.c
newlib/libc/search/twalk.c
newlib/libc/search/hash_buf.c
newlib/libc/search/hcreate.c
newlib/libc/search/hash_func.c
newlib/libc/sys/arm/access.c
newlib/libc/sys/arm/aeabi_atexit.c
newlib/libc/locale/uselocale.c
newlib/libc/locale/locale.c
newlib/libc/locale/newlocale.c
newlib/libc/locale/lmessages.c
newlib/libc/locale/lctype.c
newlib/libc/locale/duplocale.c
newlib/libc/locale/nl_langinfo.c
newlib/libc/locale/lmonetary.c
newlib/libc/locale/lnumeric.c
newlib/libc/locale/localeconv.c
newlib/libc/locale/freelocale.c
newlib/libc/locale/timelocal.c
newlib/libc/misc/__dprintf.c
newlib/libc/misc/ffs.c
newlib/libc/misc/unctrl.c
newlib/libc/misc/fini.c
newlib/libc/misc/init.c
newlib/libc/ssp/stpncpy_chk.c
newlib/libc/ssp/strncpy_chk.c
newlib/libc/ssp/memcpy_chk.c
newlib/libc/ssp/mempcpy_chk.c
newlib/libc/ssp/snprintf_chk.c
newlib/libc/ssp/strncat_chk.c
newlib/libc/ssp/memset_chk.c
newlib/libc/ssp/strcpy_chk.c
newlib/libc/ssp/stpcpy_chk.c
newlib/libc/ssp/strcat_chk.c
newlib/libc/ssp/memmove_chk.c
newlib/libc/ssp/sprintf_chk.c
newlib/libc/ssp/vsprintf_chk.c
newlib/libc/ssp/chk_fail.c
newlib/libc/ssp/stack_protector.c
newlib/libc/ssp/vsnprintf_chk.c
newlib/libc/ssp/gets_chk.c
newlib/libc/time/gettzinfo.c
newlib/libc/time/tzlock.c
newlib/libc/time/tzcalc_limits.c
newlib/libc/time/mktime.c
newlib/libc/time/tzset_r.c
newlib/libc/time/difftime.c
newlib/libc/time/ctime.c
newlib/libc/time/clock.c
newlib/libc/time/tzvars.c
newlib/libc/time/month_lengths.c
newlib/libc/time/strftime.c
newlib/libc/time/strptime.c
newlib/libc/time/wcsftime.c
newlib/libc/time/asctime_r.c
newlib/libc/time/lcltime.c
newlib/libc/time/tzset.c
newlib/libc/time/asctime.c
newlib/libc/time/lcltime_r.c
newlib/libc/time/time.c
newlib/libc/time/gmtime_r.c
newlib/libc/time/gmtime.c
newlib/libc/time/ctime_r.c
newlib/libc/machine/arm/strlen-stub.c
newlib/libc/machine/arm/strcpy.c
newlib/libc/machine/arm/strcmp.c
newlib/libc/machine/arm/strlen.c
newlib/libc/machine/arm/aeabi_memcpy-armv7a.c
newlib/libc/machine/arm/setjmp.c
newlib/libc/machine/arm/aeabi_memcpy.c
newlib/libc/machine/arm/aeabi_memclr.c
newlib/libc/machine/arm/memchr.c
newlib/libc/machine/arm/aeabi_memset-soft.c
newlib/libc/machine/arm/memcpy.c
newlib/libc/machine/arm/memcpy-stub.c
newlib/libc/machine/arm/aeabi_memmove-soft.c
newlib/libc/machine/arm/aeabi_memmove.c
newlib/libc/machine/arm/aeabi_memset.c
newlib/libc/machine/arm/memchr-stub.c
newlib/libc/stdio/fflush_u.c
newlib/libc/stdio/putchar_u.c
newlib/libc/stdio/fwrite_u.c
newlib/libc/stdio/ungetwc.c
newlib/libc/stdio/vsiprintf.c
newlib/libc/stdio/fopencookie.c
newlib/libc/stdio/vfwscanf.c
newlib/libc/stdio/vfiscanf.c
newlib/libc/stdio/asiprintf.c
newlib/libc/stdio/fgets_u.c
newlib/libc/stdio/wbuf.c
newlib/libc/stdio/getc_u.c
newlib/libc/stdio/makebuf.c
newlib/libc/stdio/getdelim.c
newlib/libc/stdio/fseek.c
newlib/libc/stdio/vfiwscanf.c
newlib/libc/stdio/sniprintf.c
newlib/libc/stdio/diprintf.c
newlib/libc/stdio/vscanf.c
newlib/libc/stdio/fiprintf.c
newlib/libc/stdio/iscanf.c
newlib/libc/stdio/fdopen.c
newlib/libc/stdio/vdiprintf.c
newlib/libc/stdio/clearerr.c
newlib/libc/stdio/fputwc.c
newlib/libc/stdio/getline.c
newlib/libc/stdio/fputc.c
newlib/libc/stdio/ferror_u.c
newlib/libc/stdio/putc_u.c
newlib/libc/stdio/svfiscanf.c
newlib/libc/stdio/fileno.c
newlib/libc/stdio/puts.c
newlib/libc/stdio/svfiwscanf.c
newlib/libc/stdio/vfwprintf.c
newlib/libc/stdio/feof.c
newlib/libc/stdio/tmpnam.c
newlib/libc/stdio/swprintf.c
newlib/libc/stdio/fgetwc_u.c
newlib/libc/stdio/viscanf.c
newlib/libc/stdio/clearerr_u.c
newlib/libc/stdio/vsiscanf.c
newlib/libc/stdio/vfiprintf.c
newlib/libc/stdio/fsetlocking.c
newlib/libc/stdio/fwalk.c
newlib/libc/stdio/fputws.c
newlib/libc/stdio/svfiprintf.c
newlib/libc/stdio/svfwscanf.c
newlib/libc/stdio/setbuf.c
newlib/libc/stdio/svfiwprintf.c
newlib/libc/stdio/tmpfile.c
newlib/libc/stdio/fread.c
newlib/libc/stdio/fputwc_u.c
newlib/libc/stdio/svfscanf.c
newlib/libc/stdio/getchar_u.c
newlib/libc/stdio/fopen.c
newlib/libc/stdio/vasnprintf.c
newlib/libc/stdio/vwscanf.c
newlib/libc/stdio/sccl.c
newlib/libc/stdio/rename.c
newlib/libc/stdio/ferror.c
newlib/libc/stdio/vdprintf.c
newlib/libc/stdio/vfscanf.c
newlib/libc/stdio/putwchar_u.c
newlib/libc/stdio/asniprintf.c
newlib/libc/stdio/fputc_u.c
newlib/libc/stdio/dprintf.c
newlib/libc/stdio/fiscanf.c
newlib/libc/stdio/setlinebuf.c
newlib/libc/stdio/asprintf.c
newlib/libc/stdio/setbuffer.c
newlib/libc/stdio/fputws_u.c
newlib/libc/stdio/wscanf.c
newlib/libc/stdio/open_memstream.c
newlib/libc/stdio/vsniprintf.c
newlib/libc/stdio/ungetc.c
newlib/libc/stdio/vswscanf.c
newlib/libc/stdio/getwchar_u.c
newlib/libc/stdio/ftello.c
newlib/libc/stdio/fgetpos.c
newlib/libc/stdio/ftell.c
newlib/libc/stdio/stdio_ext.c
newlib/libc/stdio/funopen.c
newlib/libc/stdio/scanf.c
newlib/libc/stdio/iprintf.c
newlib/libc/stdio/vfiwprintf.c
newlib/libc/stdio/fread_u.c
newlib/libc/stdio/wsetup.c
newlib/libc/stdio/refill.c
newlib/libc/stdio/fwprintf.c
newlib/libc/stdio/fpurge.c
newlib/libc/stdio/vasiprintf.c
newlib/libc/stdio/fclose.c
newlib/libc/stdio/fcloseall.c
newlib/libc/stdio/fwide.c
newlib/libc/stdio/getchar.c
newlib/libc/stdio/rget.c
newlib/libc/stdio/fileno_u.c
newlib/libc/stdio/perror.c
newlib/libc/stdio/vsprintf.c
newlib/libc/stdio/fputs_u.c
newlib/libc/stdio/vsnprintf.c
newlib/libc/stdio/getwc_u.c
newlib/libc/stdio/setvbuf.c
newlib/libc/stdio/sscanf.c
newlib/libc/stdio/fseeko.c
newlib/libc/stdio/findfp.c
newlib/libc/stdio/feof_u.c
newlib/libc/stdio/stdio.c
newlib/libc/stdio/fmemopen.c
newlib/libc/stdio/fscanf.c
newlib/libc/stdio/putchar.c
newlib/libc/stdio/fsetpos.c
newlib/libc/stdio/fprintf.c
newlib/libc/stdio/putc.c
newlib/libc/stdio/vasprintf.c
newlib/libc/stdio/fgetws_u.c
newlib/libc/stdio/fwscanf.c
newlib/libc/stdio/getw.c
newlib/libc/stdio/fgetws.c
newlib/libc/stdio/vsscanf.c
newlib/libc/stdio/vasniprintf.c
newlib/libc/stdio/fgets.c
newlib/libc/stdio/putwc_u.c
newlib/libc/stdio/viprintf.c
newlib/libc/stdio/siscanf.c
newlib/libc/stdio/getwc.c
newlib/libc/stdio/vfprintf.c
newlib/libc/stdio/printf.c
newlib/libc/stdio/snprintf.c
newlib/libc/stdio/getwchar.c
newlib/libc/stdio/fgetc.c
newlib/libc/stdio/svfwprintf.c
newlib/libc/stdio/fflush.c
newlib/libc/stdio/asnprintf.c
newlib/libc/stdio/fgetc_u.c
newlib/libc/stdio/sprintf.c
newlib/libc/stdio/freopen.c
newlib/libc/stdio/gets.c
newlib/libc/stdio/fvwrite.c
newlib/libc/stdio/fwrite.c
newlib/libc/stdio/mktemp.c
newlib/libc/stdio/vswprintf.c
newlib/libc/stdio/putwchar.c
newlib/libc/stdio/svfprintf.c
newlib/libc/stdio/flags.c
newlib/libc/stdio/fgetwc.c
newlib/libc/stdio/fputs.c
newlib/libc/stdio/wprintf.c
newlib/libc/stdio/vprintf.c
newlib/libc/stdio/remove.c
newlib/libc/stdio/rewind.c
newlib/libc/stdio/putwc.c
newlib/libc/stdio/putw.c
newlib/libc/stdio/getc.c
newlib/libc/stdio/swscanf.c
newlib/libc/stdio/vwprintf.c
newlib/libc/stdio/siprintf.c
newlib/libc/argz/argz_create.c
newlib/libc/argz/argz_append.c
newlib/libc/argz/argz_extract.c
newlib/libc/argz/envz_merge.c
newlib/libc/argz/envz_remove.c
newlib/libc/argz/argz_insert.c
newlib/libc/argz/envz_get.c
newlib/libc/argz/argz_create_sep.c
newlib/libc/argz/envz_entry.c
newlib/libc/argz/argz_add_sep.c
newlib/libc/argz/buf_findstr.c
newlib/libc/argz/argz_delete.c
newlib/libc/argz/argz_next.c
newlib/libc/argz/argz_stringify.c
newlib/libc/argz/dummy.c
newlib/libc/argz/envz_strip.c
newlib/libc/argz/argz_add.c
newlib/libc/argz/envz_add.c
newlib/libc/argz/argz_count.c
newlib/libc/argz/argz_replace.c
newlib/libc/string/memmove.c
newlib/libc/string/wcwidth.c
newlib/libc/string/wcsnlen.c
newlib/libc/string/strcpy.c
newlib/libc/string/strxfrm.c
newlib/libc/string/wmemset.c
newlib/libc/string/strcmp.c
newlib/libc/string/strlen.c
newlib/libc/string/rawmemchr.c
newlib/libc/string/strlcat.c
newlib/libc/string/bcopy.c
newlib/libc/string/strnstr.c
newlib/libc/string/timingsafe_memcmp.c
newlib/libc/string/timingsafe_bcmp.c
newlib/libc/string/wcstok.c
newlib/libc/string/strchr.c
newlib/libc/string/wcsxfrm_l.c
newlib/libc/string/strstr.c
newlib/libc/string/memmem.c
newlib/libc/string/strtok.c
newlib/libc/string/memcmp.c
newlib/libc/string/wmemmove.c
newlib/libc/string/wcsncat.c
newlib/libc/string/wcpcpy.c
newlib/libc/string/ffsl.c
newlib/libc/string/strspn.c
newlib/libc/string/strnlen.c
newlib/libc/string/flsll.c
newlib/libc/string/wcslen.c
newlib/libc/string/wcspbrk.c
newlib/libc/string/flsl.c
newlib/libc/string/rindex.c
newlib/libc/string/strpbrk.c
newlib/libc/string/strcat.c
newlib/libc/string/wcsstr.c
newlib/libc/string/strncpy.c
newlib/libc/string/wcscat.c
newlib/libc/string/strsignal.c
newlib/libc/string/wmemcpy.c
newlib/libc/string/wcsncmp.c
newlib/libc/string/wcsdup.c
newlib/libc/string/strncasecmp.c
newlib/libc/string/strupr.c
newlib/libc/string/wcschr.c
newlib/libc/string/mempcpy.c
newlib/libc/string/strncmp.c
newlib/libc/string/wcscasecmp_l.c
newlib/libc/string/strlwr.c
newlib/libc/string/memchr.c
newlib/libc/string/wcsspn.c
newlib/libc/string/strdup_r.c
newlib/libc/string/wcsncasecmp_l.c
newlib/libc/string/strcspn.c
newlib/libc/string/bzero.c
newlib/libc/string/stpcpy.c
newlib/libc/string/strcoll.c
newlib/libc/string/strerror.c
newlib/libc/string/memset.c
newlib/libc/string/wcscmp.c
newlib/libc/string/wcscasecmp.c
newlib/libc/string/strndup_r.c
newlib/libc/string/stpncpy.c
newlib/libc/string/strcasecmp.c
newlib/libc/string/wmemcmp.c
newlib/libc/string/wcsncpy.c
newlib/libc/string/wmempcpy.c
newlib/libc/string/wcpncpy.c
newlib/libc/string/strxfrm_l.c
newlib/libc/string/wcsxfrm.c
newlib/libc/string/gnu_basename.c
newlib/libc/string/wcscoll_l.c
newlib/libc/string/fls.c
newlib/libc/string/wcslcpy.c
newlib/libc/string/wcsncasecmp.c
newlib/libc/string/ffsll.c
newlib/libc/string/memcpy.c
newlib/libc/string/wcswidth.c
newlib/libc/string/wcscspn.c
newlib/libc/string/wcsrchr.c
newlib/libc/string/strncat.c
newlib/libc/string/strtok_r.c
newlib/libc/string/explicit_bzero.c
newlib/libc/string/strcasestr.c
newlib/libc/string/strndup.c
newlib/libc/string/strverscmp.c
newlib/libc/string/xpg_strerror_r.c
newlib/libc/string/strdup.c
newlib/libc/string/bcmp.c
newlib/libc/string/strerror_r.c
newlib/libc/string/strcoll_l.c
newlib/libc/string/strchrnul.c
newlib/libc/string/strrchr.c
newlib/libc/string/wmemchr.c
newlib/libc/string/memccpy.c
newlib/libc/string/u_strerr.c
newlib/libc/string/swab.c
newlib/libc/string/strsep.c
newlib/libc/string/strcasecmp_l.c
newlib/libc/string/wcscpy.c
newlib/libc/string/wcscoll.c
newlib/libc/string/strncasecmp_l.c
newlib/libc/string/memrchr.c
newlib/libc/string/wcslcat.c
newlib/libc/string/index.c
newlib/libc/string/strlcpy.c
newlib/libc/errno/errno.c
''')

libm_src = Split('''
newlib/libm/common/s_fdim.c
newlib/libm/common/nearbyintl.c
newlib/libm/common/sf_scalbln.c
newlib/libm/common/s_round.c
newlib/libm/common/s_fmin.c
newlib/libm/common/s_nextafter.c
newlib/libm/common/acoshl.c
newlib/libm/common/log10l.c
newlib/libm/common/lgammal.c
newlib/libm/common/s_expm1.c
newlib/libm/common/sinhl.c
newlib/libm/common/sf_fpclassify.c
newlib/libm/common/sf_exp10.c
newlib/libm/common/sf_expm1.c
newlib/libm/common/s_isinfd.c
newlib/libm/common/s_cbrt.c
newlib/libm/common/powl.c
newlib/libm/common/sf_llrint.c
newlib/libm/common/modfl.c
newlib/libm/common/s_remquo.c
newlib/libm/common/sf_log_data.c
newlib/libm/common/s_lround.c
newlib/libm/common/llrintl.c
newlib/libm/common/s_isinf.c
newlib/libm/common/sf_nextafter.c
newlib/libm/common/s_copysign.c
newlib/libm/common/roundl.c
newlib/libm/common/fminl.c
newlib/libm/common/hypotl.c
newlib/libm/common/tanl.c
newlib/libm/common/fabsl.c
newlib/libm/common/nexttowardl.c
newlib/libm/common/copysignl.c
newlib/libm/common/sf_logb.c
newlib/libm/common/s_matherr.c
newlib/libm/common/remainderl.c
newlib/libm/common/sf_finite.c
newlib/libm/common/sf_trunc.c
newlib/libm/common/sf_modf.c
newlib/libm/common/rintl.c
newlib/libm/common/s_llrint.c
newlib/libm/common/nexttoward.c
newlib/libm/common/tgammal.c
newlib/libm/common/lrintl.c
newlib/libm/common/nextafterl.c
newlib/libm/common/asinl.c
newlib/libm/common/sf_scalbn.c
newlib/libm/common/sf_fma.c
newlib/libm/common/logbl.c
newlib/libm/common/s_nearbyint.c
newlib/libm/common/sf_ilogb.c
newlib/libm/common/s_finite.c
newlib/libm/common/floorl.c
newlib/libm/common/fmal.c
newlib/libm/common/sf_fmax.c
newlib/libm/common/log2l.c
newlib/libm/common/sf_fdim.c
newlib/libm/common/sf_log1p.c
newlib/libm/common/sf_round.c
newlib/libm/common/lroundl.c
newlib/libm/common/sf_lround.c
newlib/libm/common/nanl.c
newlib/libm/common/sf_pow.c
newlib/libm/common/s_llround.c
newlib/libm/common/s_fma.c
newlib/libm/common/cosl.c
newlib/libm/common/ceill.c
newlib/libm/common/s_fmax.c
newlib/libm/common/sf_lrint.c
newlib/libm/common/s_isnand.c
newlib/libm/common/ldexpl.c
newlib/libm/common/s_scalbn.c
newlib/libm/common/scalbnl.c
newlib/libm/common/s_scalbln.c
newlib/libm/common/sf_log2.c
newlib/libm/common/s_lib_ver.c
newlib/libm/common/atanl.c
newlib/libm/common/sf_isnan.c
newlib/libm/common/s_modf.c
newlib/libm/common/sf_log.c
newlib/libm/common/s_trunc.c
newlib/libm/common/llroundl.c
newlib/libm/common/ilogbl.c
newlib/libm/common/sf_pow_log2_data.c
newlib/libm/common/sf_exp2_data.c
newlib/libm/common/sinl.c
newlib/libm/common/acosl.c
newlib/libm/common/logl.c
newlib/libm/common/truncl.c
newlib/libm/common/s_infinity.c
newlib/libm/common/expl.c
newlib/libm/common/sf_infinity.c
newlib/libm/common/sf_log2_data.c
newlib/libm/common/sf_cbrt.c
newlib/libm/common/nexttowardf.c
newlib/libm/common/sf_pow10.c
newlib/libm/common/log1pl.c
newlib/libm/common/atanhl.c
newlib/libm/common/sf_exp2.c
newlib/libm/common/frexpl.c
newlib/libm/common/sf_exp.c
newlib/libm/common/exp2l.c
newlib/libm/common/cbrtl.c
newlib/libm/common/s_pow10.c
newlib/libm/common/s_signbit.c
newlib/libm/common/coshl.c
newlib/libm/common/sf_rint.c
newlib/libm/common/remquol.c
newlib/libm/common/sf_llround.c
newlib/libm/common/s_nan.c
newlib/libm/common/sf_isinf.c
newlib/libm/common/atan2l.c
newlib/libm/common/sf_fmin.c
newlib/libm/common/s_log2.c
newlib/libm/common/sf_isnanf.c
newlib/libm/common/scalblnl.c
newlib/libm/common/s_lrint.c
newlib/libm/common/s_log1p.c
newlib/libm/common/sf_nearbyint.c
newlib/libm/common/sf_isinff.c
newlib/libm/common/sf_copysign.c
newlib/libm/common/fdiml.c
newlib/libm/common/s_exp10.c
newlib/libm/common/fmodl.c
newlib/libm/common/s_isnan.c
newlib/libm/common/expm1l.c
newlib/libm/common/tanhl.c
newlib/libm/common/asinhl.c
newlib/libm/common/sf_nan.c
newlib/libm/common/erfl.c
newlib/libm/common/s_rint.c
newlib/libm/common/math_errf.c
newlib/libm/common/sqrtl.c
newlib/libm/common/erfcl.c
newlib/libm/common/sf_remquo.c
newlib/libm/common/s_ilogb.c
newlib/libm/common/s_logb.c
newlib/libm/common/fmaxl.c
newlib/libm/common/sl_finite.c
newlib/libm/common/s_fpclassify.c
newlib/libm/math/s_ldexp.c
newlib/libm/math/wf_j0.c
newlib/libm/math/s_sin.c
newlib/libm/math/ef_cosh.c
newlib/libm/math/s_asinh.c
newlib/libm/math/el_hypot.c
newlib/libm/math/wr_lgamma.c
newlib/libm/math/s_tan.c
newlib/libm/math/e_atan2.c
newlib/libm/math/sf_cos.c
newlib/libm/math/w_log10.c
newlib/libm/math/w_exp2.c
newlib/libm/math/w_j0.c
newlib/libm/math/wf_asin.c
newlib/libm/math/w_j1.c
newlib/libm/math/e_acos.c
newlib/libm/math/e_j0.c
newlib/libm/math/w_hypot.c
newlib/libm/math/e_sinh.c
newlib/libm/math/ef_sinh.c
newlib/libm/math/kf_rem_pio2.c
newlib/libm/math/e_hypot.c
newlib/libm/math/sf_signif.c
newlib/libm/math/w_log.c
newlib/libm/math/e_j1.c
newlib/libm/math/ef_atanh.c
newlib/libm/math/e_scalb.c
newlib/libm/math/s_ceil.c
newlib/libm/math/k_standard.c
newlib/libm/math/w_drem.c
newlib/libm/math/ef_acosh.c
newlib/libm/math/er_gamma.c
newlib/libm/math/k_sin.c
newlib/libm/math/wf_cosh.c
newlib/libm/math/wf_jn.c
newlib/libm/math/e_pow.c
newlib/libm/math/w_jn.c
newlib/libm/math/e_asin.c
newlib/libm/math/s_erf.c
newlib/libm/math/w_cosh.c
newlib/libm/math/s_frexp.c
newlib/libm/math/wf_lgamma.c
newlib/libm/math/wrf_gamma.c
newlib/libm/math/kf_cos.c
newlib/libm/math/wf_scalb.c
newlib/libm/math/ef_exp.c
newlib/libm/math/sf_ceil.c
newlib/libm/math/sf_asinh.c
newlib/libm/math/wf_atan2.c
newlib/libm/math/w_scalb.c
newlib/libm/math/sf_erf.c
newlib/libm/math/wf_pow.c
newlib/libm/math/ef_asin.c
newlib/libm/math/e_log.c
newlib/libm/math/e_jn.c
newlib/libm/math/e_sqrt.c
newlib/libm/math/er_lgamma.c
newlib/libm/math/e_cosh.c
newlib/libm/math/sf_fabs.c
newlib/libm/math/erf_lgamma.c
newlib/libm/math/wf_log.c
newlib/libm/math/kf_tan.c
newlib/libm/math/erf_gamma.c
newlib/libm/math/w_asin.c
newlib/libm/math/e_atanh.c
newlib/libm/math/sf_tan.c
newlib/libm/math/wf_log10.c
newlib/libm/math/w_remainder.c
newlib/libm/math/k_tan.c
newlib/libm/math/wr_gamma.c
newlib/libm/math/ef_log.c
newlib/libm/math/ef_remainder.c
newlib/libm/math/s_tanh.c
newlib/libm/math/kf_sin.c
newlib/libm/math/w_acosh.c
newlib/libm/math/k_cos.c
newlib/libm/math/wf_j1.c
newlib/libm/math/wf_drem.c
newlib/libm/math/wf_atanh.c
newlib/libm/math/s_fabs.c
newlib/libm/math/w_tgamma.c
newlib/libm/math/wf_log2.c
newlib/libm/math/ef_fmod.c
newlib/libm/math/e_exp.c
newlib/libm/math/sf_sin.c
newlib/libm/math/ef_pow.c
newlib/libm/math/s_cos.c
newlib/libm/math/sf_ldexp.c
newlib/libm/math/ef_atan2.c
newlib/libm/math/sf_frexp.c
newlib/libm/math/w_fmod.c
newlib/libm/math/w_pow.c
newlib/libm/math/ef_acos.c
newlib/libm/math/w_exp.c
newlib/libm/math/e_log10.c
newlib/libm/math/wf_hypot.c
newlib/libm/math/wf_acosh.c
newlib/libm/math/w_lgamma.c
newlib/libm/math/sf_floor.c
newlib/libm/math/w_acos.c
newlib/libm/math/e_fmod.c
newlib/libm/math/w_atan2.c
newlib/libm/math/wf_remainder.c
newlib/libm/math/ef_j0.c
newlib/libm/math/wf_acos.c
newlib/libm/math/ef_j1.c
newlib/libm/math/wf_exp.c
newlib/libm/math/w_gamma.c
newlib/libm/math/wf_gamma.c
newlib/libm/math/sf_tanh.c
newlib/libm/math/e_rem_pio2.c
newlib/libm/math/wf_sincos.c
newlib/libm/math/s_signif.c
newlib/libm/math/wf_exp2.c
newlib/libm/math/ef_jn.c
newlib/libm/math/wrf_lgamma.c
newlib/libm/math/ef_hypot.c
newlib/libm/math/sf_atan.c
newlib/libm/math/ef_sqrt.c
newlib/libm/math/k_rem_pio2.c
newlib/libm/math/w_sincos.c
newlib/libm/math/wf_sinh.c
newlib/libm/math/wf_fmod.c
newlib/libm/math/s_floor.c
newlib/libm/math/e_remainder.c
newlib/libm/math/ef_scalb.c
newlib/libm/math/ef_log10.c
newlib/libm/math/s_atan.c
newlib/libm/math/wf_sqrt.c
newlib/libm/math/w_sinh.c
newlib/libm/math/w_sqrt.c
newlib/libm/math/w_atanh.c
newlib/libm/math/wf_tgamma.c
newlib/libm/math/ef_rem_pio2.c
newlib/libm/math/e_acosh.c
newlib/libm/machine/arm/s_round.c
newlib/libm/machine/arm/s_ceil.c
newlib/libm/machine/arm/sf_trunc.c
newlib/libm/machine/arm/sf_ceil.c
newlib/libm/machine/arm/e_sqrt.c
newlib/libm/machine/arm/s_nearbyint.c
newlib/libm/machine/arm/sf_round.c
newlib/libm/machine/arm/s_trunc.c
newlib/libm/machine/arm/sf_floor.c
newlib/libm/machine/arm/sf_rint.c
newlib/libm/machine/arm/sf_nearbyint.c
newlib/libm/machine/arm/s_rint.c
newlib/libm/machine/arm/ef_sqrt.c
newlib/libm/machine/arm/s_floor.c
newlib/libm/complex/cprojf.c
newlib/libm/complex/ccoshl.c
newlib/libm/complex/cpowf.c
newlib/libm/complex/cacosl.c
newlib/libm/complex/carg.c
newlib/libm/complex/cargl.c
newlib/libm/complex/creal.c
newlib/libm/complex/catanf.c
newlib/libm/complex/ccosl.c
newlib/libm/complex/casinh.c
newlib/libm/complex/cacosf.c
newlib/libm/complex/clogl.c
newlib/libm/complex/catanh.c
newlib/libm/complex/conj.c
newlib/libm/complex/casinl.c
newlib/libm/complex/cpowl.c
newlib/libm/complex/clogf.c
newlib/libm/complex/catanhf.c
newlib/libm/complex/conjl.c
newlib/libm/complex/cpow.c
newlib/libm/complex/crealf.c
newlib/libm/complex/creall.c
newlib/libm/complex/ccos.c
newlib/libm/complex/ctan.c
newlib/libm/complex/ctanhl.c
newlib/libm/complex/cacoshf.c
newlib/libm/complex/csqrt.c
newlib/libm/complex/csqrtl.c
newlib/libm/complex/csinhf.c
newlib/libm/complex/clog.c
newlib/libm/complex/catanl.c
newlib/libm/complex/ctanhf.c
newlib/libm/complex/casinhl.c
newlib/libm/complex/ccosh.c
newlib/libm/complex/conjf.c
newlib/libm/complex/cimagf.c
newlib/libm/complex/csinf.c
newlib/libm/complex/cephes_subrl.c
newlib/libm/complex/cexpl.c
newlib/libm/complex/clog10.c
newlib/libm/complex/csinl.c
newlib/libm/complex/csinh.c
newlib/libm/complex/ccoshf.c
newlib/libm/complex/casinhf.c
newlib/libm/complex/ctanf.c
newlib/libm/complex/cprojl.c
newlib/libm/complex/csin.c
newlib/libm/complex/csinhl.c
newlib/libm/complex/cacoshl.c
newlib/libm/complex/cephes_subr.c
newlib/libm/complex/clog10f.c
newlib/libm/complex/cabsl.c
newlib/libm/complex/cabs.c
newlib/libm/complex/ccosf.c
newlib/libm/complex/catan.c
newlib/libm/complex/cexp.c
newlib/libm/complex/ctanh.c
newlib/libm/complex/cimag.c
newlib/libm/complex/ctanl.c
newlib/libm/complex/cproj.c
newlib/libm/complex/cargf.c
newlib/libm/complex/cacosh.c
newlib/libm/complex/cacos.c
newlib/libm/complex/cephes_subrf.c
newlib/libm/complex/casinf.c
newlib/libm/complex/cexpf.c
newlib/libm/complex/cimagl.c
newlib/libm/complex/csqrtf.c
newlib/libm/complex/cabsf.c
newlib/libm/complex/catanhl.c
newlib/libm/complex/casin.c
''')

src += libc_src
CPPPATH += ['newlib/libc/include']

if GetDepend('NEWLIB_USING_LIBM'):
    src += libm_src

src     = [ newlib_path + '/' + item for item in src]
CPPPATH = [ newlib_path + '/' + item for item in CPPPATH]

group = DefineGroup('newlib', src, depend = ['PKG_USING_NEWLIB'], CPPPATH = CPPPATH)

Return('group')
